version: '3.8'
services:
  stats-db:
    image: postgres:15-alpine
    container_name: stats-db
    environment:
      POSTGRES_DB: ewm-stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  stats-server:
    build: ./stats/stats-server
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm-stats
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 9090
